### ISSUE TITLE
ImportError: No module named fast_jtnn

### ISSUE THREAD

**Issue by fanmengdan** [wengong-jin/iclr19-graph2graph#2]
when i run "python ../scripts/preprocess.py --train ../data/logp04/train_pairs.txt --ncpu 8", I met this problem “ImportError: No module named fast_jtnn”

**Comment by wengong-jin** [comment]
Please run 
```
export PYTHONPATH=$path_to_repo/iclr19-graph2graph
```

**Comment by fanmengdan** [comment]
> Please run
> 
> ```
> export PYTHONPATH=$path_to_repo/iclr19-graph2graph
> ```

thanks
