### ISSUE TITLE
Some questions for Experiments :)

### ISSUE THREAD

**Issue by ksh981214** [wengong-jin/iclr19-graph2graph#3]
Thank you for your good paper. And while we were experimenting with the paper, there were some problems that left an issue.

1. all files at path "diff_vae/val_scripts/", the initial condition of i in for-loop is 1 not 0. 
However, Model files are made from 'model-iter.0. to model-iter.n'. Shouldn't the initial conditions be revised(1-->0)?

2. In validation, ```bash val_scripts/valid_logp04.sh models/logp04 10``` --> ```bash val_scripts/valid_logp04.sh **new**models/logp04 10``` , is it right?

3. When I run validation, I can't figure out how to solve this error. The same error occurs if I try to execute using the model of 'models/'. How do I fix this?
![runtime error](https://user-images.githubusercontent.com/38184045/75955202-b92f3300-5ef8-11ea-88aa-175430ec9a06.png)

Thank you !

**Comment by wengong-jin** [comment]
Hi,

1. In most cases, the first model checkpoint does not perform well, so I just skipped that.
2. Yes, the validation scripts need to be modified accordingly (e.g., changing folder names, etc)
3. Please try removing '--share_embedding' argument. I think this is the problem. If that's the case, I will change the validation script.

**Comment by ksh981214** [comment]
Works well :) ! 

Thank u!
