### ISSUE TITLE
Error in loading state_dict for DiffVAE

### ISSUE THREAD

**Issue by SejeongPark8354** [wengong-jin/iclr19-graph2graph#5]
First of all, thank you for your wonderful study in molecular generation. 
I am learning a lot from your research. 
When I try testing process like below figure, error in loading state_dic was occurred. 
(same problem: model.iter-5 in logp04, logp06 in diff_vae, model.iter-3 in qed in diff_vae_gan, etc.)
Is there any solution to this problem? 
I'll wait your help. 
Thanks. 

![image](https://user-images.githubusercontent.com/65217511/93980885-2e415780-fdba-11ea-8625-de5438cd3fdb.png)

**Comment by wengong-jin** [comment]
Sorry for my late reply. Please run the script with --hidden_size 330
